version: "3.5"

services:
  maka_dev:
    ports:
      - 8000:8000
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: "maka_dev"
    volumes:
      - ../../maka-koa-server:/usr/src/app/src
